// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_products_slug_ from "./routes/api/products/[slug].ts";
import * as $api_products_index from "./routes/api/products/index.ts";
import * as $cart from "./routes/cart.tsx";
import * as $checkout from "./routes/checkout.tsx";
import * as $index from "./routes/index.tsx";
import * as $order_success from "./routes/order-success.tsx";
import * as $shop_slug_ from "./routes/shop/[slug].tsx";
import * as $shop_index from "./routes/shop/index.tsx";
import * as $AddToCart from "./islands/AddToCart.tsx";
import * as $CartBadge from "./islands/CartBadge.tsx";
import * as $CartView from "./islands/CartView.tsx";
import * as $ChatWidget from "./islands/ChatWidget.tsx";
import * as $CheckoutForm from "./islands/CheckoutForm.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $MobileMenu from "./islands/MobileMenu.tsx";
import * as $ProductGallery from "./islands/ProductGallery.tsx";
import * as $ScrollToTop from "./islands/ScrollToTop.tsx";
import * as $SearchBar from "./islands/SearchBar.tsx";
import * as $SearchModal from "./islands/SearchModal.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/products/[slug].ts": $api_products_slug_,
    "./routes/api/products/index.ts": $api_products_index,
    "./routes/cart.tsx": $cart,
    "./routes/checkout.tsx": $checkout,
    "./routes/index.tsx": $index,
    "./routes/order-success.tsx": $order_success,
    "./routes/shop/[slug].tsx": $shop_slug_,
    "./routes/shop/index.tsx": $shop_index,
  },
  islands: {
    "./islands/AddToCart.tsx": $AddToCart,
    "./islands/CartBadge.tsx": $CartBadge,
    "./islands/CartView.tsx": $CartView,
    "./islands/ChatWidget.tsx": $ChatWidget,
    "./islands/CheckoutForm.tsx": $CheckoutForm,
    "./islands/Counter.tsx": $Counter,
    "./islands/MobileMenu.tsx": $MobileMenu,
    "./islands/ProductGallery.tsx": $ProductGallery,
    "./islands/ScrollToTop.tsx": $ScrollToTop,
    "./islands/SearchBar.tsx": $SearchBar,
    "./islands/SearchModal.tsx": $SearchModal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
